"""create contracts table

Revision ID: 7f300483f312
Revises: eac2dcd14b95
Create Date: 2026-07-14 19:42:48.783989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f300483f312'
down_revision: Union[str, Sequence[str], None] = 'eac2dcd14b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('project_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cover_letter', mysql.TEXT(), nullable=False),
    sa.Column('bid_amount', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('freelancer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], name=op.f('proposals_ibfk_1')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('proposals_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('budget', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('projects_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('freelancer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('contracts_ibfk_2')),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], name=op.f('contracts_ibfk_3')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('contracts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('project_id'), 'contracts', ['project_id'], unique=True)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    # ### end Alembic commands ###
